spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/management?useUnicode=true&amp;autoReconnect=true&amp;characterEncoding=utf8
    username: root
    password: root
